/*
    This file is part of libdjinterop.

    libdjinterop is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    libdjinterop is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with libdjinterop.  If not, see <http://www.gnu.org/licenses/>.
 */

// This translation unit links libdjinterop against the rekordcrate cxx bridge.
// It is the *only* file that includes the cxx-generated header; the rest of the
// adapter talks to `rekordcrate_writer` via plain C++ structs, keeping the cxx
// dependency localized. The header is generated by Corrosion's
// `corrosion_add_cxxbridge` target (rekordcrate-cpp); Corrosion places it under
// a directory named after that target, hence `rekordcrate-cpp/cpp.h`.

#include "rekordcrate_writer.hpp"

#include <rekordcrate-cpp/cpp.h>  // cxx-generated from rekordcrate::src/cpp.rs
#include <rust/cxx.h>

#include <stdexcept>
#include <utility>

namespace djinterop::rekordcrate
{
namespace
{
/// Translate the adapter's plain `ffi_*` structs into the cxx bridge's shared
/// types, then hand them to `rekordcrate::writer_add_track`. cxx throws on the
/// Rust side as `rust::Error`; the bridge converts `Error` to a C++ exception.
::rekordcrate::Track to_ffi_track(
    const std::string& file_path, const std::string& filename,
    const std::string& title, const std::string& artist,
    const std::string& album, const std::string& genre,
    const std::string& comment, uint32_t sample_rate, uint32_t bitrate,
    const std::optional<ffi_performance_data>& performance,
    uint64_t sample_count)
{
    ::rekordcrate::Track t = ::rekordcrate::track_default();
    t.file_path = file_path;
    t.filename = filename;
    t.title = title;
    t.artist = artist;
    t.album = album;
    t.genre = genre;
    t.comment = comment;
    t.sample_rate = sample_rate;
    t.bitrate = bitrate;
    t.sample_count = sample_count;

    if (performance)
    {
        auto& p = t.performance;
        p.bpm = performance->bpm;
        p.main_cue_sample = performance->main_cue_sample;
        p.waveform_detail.reserve(performance->waveform_detail.size());
        for (auto& e : performance->waveform_detail)
        {
            p.waveform_detail.push_back(
                ::rekordcrate::WaveformEntry{e.low, e.mid, e.high});
        }
        p.waveform_height.reserve(performance->waveform_height.size());
        for (auto h : performance->waveform_height)
        {
            p.waveform_height.push_back(h);
        }
        p.beatgrid.reserve(performance->beatgrid.size());
        for (auto& m : performance->beatgrid)
        {
            p.beatgrid.push_back(
                ::rekordcrate::BeatgridMarker{m.index, m.sample_offset});
        }
        p.hot_cues.reserve(performance->hot_cues.size());
        for (auto& hc : performance->hot_cues)
        {
            p.hot_cues.push_back(
                ::rekordcrate::HotCueFfi{
                    hc.index, hc.label, hc.sample_offset, hc.r, hc.g, hc.b,
                    hc.a});
        }
        p.loops.reserve(performance->loops.size());
        for (auto& lp : performance->loops)
        {
            p.loops.push_back(
                ::rekordcrate::LoopFfi{
                    lp.index, lp.label, lp.start, lp.end, lp.r, lp.g, lp.b,
                    lp.a});
        }
    }
    return t;
}
}  // namespace

struct rekordcrate_writer::impl
{
    rust::Box<::rekordcrate::Writer> w;
};

rekordcrate_writer::rekordcrate_writer(const std::string& directory) :
    pimpl_{
        std::make_unique<impl>(impl{::rekordcrate::writer_create(directory)})}
{
}

rekordcrate_writer::~rekordcrate_writer() = default;

ffi_add_track_outcome rekordcrate_writer::add_track(
    const std::string& file_path, const std::string& filename,
    const std::string& title, const std::string& artist,
    const std::string& album, const std::string& genre,
    const std::string& comment, uint32_t sample_rate, uint32_t bitrate,
    std::optional<ffi_performance_data> performance, uint64_t sample_count)
{
    auto t = to_ffi_track(
        file_path, filename, title, artist, album, genre, comment, sample_rate,
        bitrate, performance, sample_count);
    auto outcome = ::rekordcrate::writer_add_track(*pimpl_->w, t);
    return ffi_add_track_outcome{outcome.id, outcome.is_new};
}

uint32_t rekordcrate_writer::create_playlist_folder(
    const std::string& name, uint32_t parent_id)
{
    return ::rekordcrate::writer_create_playlist_folder(
        *pimpl_->w, name, parent_id);
}

uint32_t rekordcrate_writer::create_playlist(
    const std::string& name, uint32_t parent_id)
{
    return ::rekordcrate::writer_create_playlist(*pimpl_->w, name, parent_id);
}

void rekordcrate_writer::add_track_to_playlist(
    uint32_t playlist_id, uint32_t track_id)
{
    ::rekordcrate::writer_add_track_to_playlist(
        *pimpl_->w, playlist_id, track_id);
}

}  // namespace djinterop::rekordcrate
